#!/usr/bin/env python3
"""
Build static knowledge base from curated design knowledge.
Outputs: public/knowledge.json

This script is automatically run before `npm run dev` and `npm run build`.
To add live-fetched content, run: node scripts/ingest.mjs
"""
import json, os, sys
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, 'public', 'knowledge.json')

def load_existing():
    """If ingest.mjs has already run and saved live data, merge with it."""
    try:
        with open(OUT) as f:
            d = json.load(f)
        # Only keep if it has live-fetched content (articles from RSS)
        if d.get('stats', {}).get('articles', 0) > 4:
            return d
    except:
        pass
    return None

# ── Curated knowledge ──────────────────────────────────────────────────────────

PRINCIPLES = [
  {"id":"p1","title":"MIT: Systems Thinking - Feedback Loops in UX","content":"Every user interface creates feedback loops. Reinforcing loops amplify behavior (notifications to engagement to more notifications). Balancing loops seek equilibrium (user fatigue to reduced usage to product changes). Great designers identify which loops exist in their product and design intentionally. MAANG bar: can you draw the causal loop diagram for your product? Can you identify the dominant loop? Example: Instagram reinforcing loop - post, likes, dopamine, post more. The design question is: does this loop create value or addiction?","source":"MIT System Dynamics","url":"https://ocw.mit.edu/courses/res-15-004-principles-of-system-dynamics-spring-2007/","tags":["systems","feedback-loops","mit"],"skillArea":"systemsThinking"},
  {"id":"p2","title":"MIT: First Principles Design Thinking","content":"Break problems to fundamental truths rather than analogy. Ask: What is the core human need? What are physical/cognitive constraints? What would be ideal with no legacy? Steps: (1) Question every assumption in the brief. (2) Identify which constraints are real vs inherited. (3) Rebuild from necessity. Applied: instead of make the button more visible, ask why is the user not completing this action? First principles prevents local optimization when global redesign is needed.","source":"MIT","url":"https://ocw.mit.edu","tags":["first-principles","problem-framing","mit"],"skillArea":"productThinking"},
  {"id":"p3","title":"MIT: Measuring Design Impact - Leading vs Lagging Indicators","content":"Leading indicators change immediately with design changes: task success rate, time on task, error rate, SUS score. Lagging indicators take weeks/months: retention, NPS, revenue, LTV. Systemic indicators: support ticket reduction, onboarding drop-off, feature adoption. MAANG interviewers always ask: how did you measure success? Define metrics BEFORE designing. Red flag: designers who only measure users liked it with no quantitative baseline.","source":"MIT","url":"https://ocw.mit.edu","tags":["metrics","measurement","impact"],"skillArea":"productThinking"},
  {"id":"p4","title":"Stanford: Empathy First - Observation over Self-Report","content":"Core d.school principle: observe what people DO, not what they say. Humans are poor at self-reporting their own behavior. Methods: fly-on-the-wall (observe without interacting), contextual inquiry (interview while user works in actual environment), diary studies (users log behavior over time), intercept testing (catch users at moment of use). MAANG bar: how many hours did you spend with real users? If less than 10 per project, your empathy is incomplete.","source":"Stanford d.school","url":"https://dschool.stanford.edu/methods","tags":["empathy","research","observation","stanford"],"skillArea":"uxExecution"},
  {"id":"p5","title":"Stanford: Creative Confidence","content":"David Kelley: creative confidence is the belief that you have ideas worth pursuing and the courage to act on them. In design teams: (1) Psychological safety enables better ideas. (2) Build-to-think, not think-to-build. (3) Yes, and not Yes, but in ideation. (4) Volume before quality: 100 bad ideas contain seeds of 3 great ones. MAANG bar: how do you create an environment where cross-functional partners contribute design ideas freely?","source":"Stanford d.school","url":"https://dschool.stanford.edu","tags":["creative-confidence","ideation","culture","stanford"],"skillArea":"communication"},
  {"id":"p6","title":"W3C: POUR Principles - Accessible Design Foundation","content":"WCAG 2.1 POUR: (1) PERCEIVABLE: text alternatives for images, captions for video, min 4.5:1 contrast for normal text, 3:1 for large text. (2) OPERABLE: all functionality by keyboard, no keyboard traps, 44px minimum touch targets, no seizure-inducing content. (3) UNDERSTANDABLE: language declared, errors identified clearly, consistent navigation. (4) ROBUST: valid HTML, ARIA roles for custom components, name/role/value for all interactive elements. MAANG bar: accessibility is not a checkbox - it is evidence of systematic quality thinking.","source":"W3C WCAG 2.1","url":"https://www.w3.org/TR/WCAG21/","tags":["pour","wcag","accessibility","w3c"],"skillArea":"uxExecution"},
  {"id":"p7","title":"W3C: Inclusive Design and the Curb-Cut Effect","content":"The curb-cut effect: features designed for people with disabilities improve experience for everyone. Captions (designed for deaf users) help ESL learners, noisy environments, ADHD. High-contrast mode helps users in bright sunlight. Voice control (motor disabilities) powers smart speakers. Designing inclusively expands your addressable market. Microsoft Inclusive Design: design for the excluded to benefit all. Permanent disability, temporary disability (broken arm), situational disability (new parent holding baby) - same solution serves all three.","source":"W3C / Microsoft Inclusive Design","url":"https://inclusive.microsoft.design/","tags":["inclusive","curb-cut","accessibility","microsoft"],"skillArea":"uxExecution"},
  {"id":"p8","title":"Google: HEART Framework for UX Metrics","content":"Google HEART: Happiness (satisfaction surveys, NPS, tracked over time), Engagement (session depth, actions per session, DAU/MAU ratio), Adoption (% of users using new feature in first 7 days), Retention (D1, D7, D30 retention curves), Task Success (completion rate, error rate, time-on-task). Usage: set Goals then identify Signals then define Metrics. Pick 2-3 metrics per project. Mistake: measuring engagement when you should measure task success. MAANG question: your HEART metrics define what your team is actually optimizing for.","source":"Google Design","url":"https://design.google","tags":["heart","metrics","google","measurement"],"skillArea":"productThinking"},
  {"id":"p9","title":"Meta: Social Product Design at Scale","content":"Meta design philosophy: (1) Products must account for social dynamics - design for the community, not just individual. (2) Network effects change design decisions - good at 100 users may be harmful at 100 million. (3) Design for most vulnerable user. (4) Meaningful interaction over passive consumption. (5) Transparency builds trust. MAANG bar for Meta: how does your design hold up when adversarial users find it? What are the abuse vectors?","source":"Meta Design","url":"https://design.facebook.com/","tags":["meta","scale","social","safety"],"skillArea":"productThinking"},
  {"id":"p10","title":"MAANG: Platform Ecosystem Design","content":"Platform design requires thinking beyond individual flows: (1) Multi-sided markets: draw all user types and their value exchange. (2) Network effects: design the flywheel explicitly - more users make product better for all. (3) API-first thinking: developer experience is a UX problem. (4) Governance at scale: who can do what, enforced through design not policy. System design interview: draw full ecosystem, identify all user types, articulate value exchange and flywheel. Designers who only think about one user type fail at MAANG scale.","source":"MAANG Curated","url":"internal","tags":["platform","ecosystem","network-effects","maang"],"skillArea":"systemsThinking"},
  {"id":"p11","title":"MAANG: AI Product Design - Designing for Uncertainty","content":"AI-powered products require handling uncertainty explicitly: (1) Confidence vs correctness - AI can be confidently wrong. Show confidence contextually. (2) Distribution shift - AI trained on historical data fails on new patterns. Design graceful degradation. (3) Explainability gap - users need to understand why AI decided something. (4) Feedback loops - biased interaction equals biased future model. Design explicit feedback mechanisms. (5) Edge cases are common in AI. MAANG bar: show me three failure modes of your AI feature and explain the UX for each.","source":"Google PAIR / MAANG Curated","url":"https://pair.withgoogle.com/","tags":["ai","ml","uncertainty","failure-modes"],"skillArea":"aiUnderstanding"},
  {"id":"p12","title":"MAANG: Stakeholder Communication - Pyramid Principle","content":"Barbara Minto Pyramid Principle for design: lead with the conclusion. Structure: (1) Headline: state your recommendation first. (2) Key line: 3 supporting arguments. (3) Supporting data: evidence for each argument. Never build up to your conclusion. Executives decide in first 30 seconds. Design presentation structure: Recommendation, Evidence, Alternatives Considered, Trade-offs, Success Metrics. MAANG pattern: good designers present like product managers - with clear POV, evidence, and next steps defined.","source":"MAANG Curated","url":"internal","tags":["communication","presentation","pyramid-principle","stakeholders"],"skillArea":"communication"},
  {"id":"p13","title":"Data-Driven Design: A/B Testing Principles","content":"A/B testing for designers: (1) Change one variable only. (2) Statistical significance: minimum p less than 0.05, typically 1000+ users per variant. (3) Practical significance: 0.01% improvement may not be worth shipping. (4) Primary and guardrail metrics: define what you optimize AND what you will not sacrifice. (5) Run for full business cycles (minimum 2 weeks). Red flags: stopping tests early when results look good, ignoring negative guardrail metrics, changing test mid-run.","source":"MAANG Curated","url":"internal","tags":["ab-testing","data","experimentation","metrics"],"skillArea":"aiUnderstanding"},
  {"id":"p14","title":"Jobs-to-be-Done: Understanding User Motivation","content":"Clayton Christensen JTBD: people hire products to make progress in their lives. Three job dimensions: (1) Functional: what they are literally trying to accomplish. (2) Emotional: how they want to feel. (3) Social: how they want to be perceived. Example: people do not hire a milkshake (product) - they hire it to make a boring commute more interesting (job). For design: understanding the job prevents feature-first thinking. MAANG bar: what evidence do you have for the job this feature is hired to do?","source":"MAANG Curated / Clayton Christensen","url":"https://hbr.org/2016/09/know-your-customers-jobs-to-be-done","tags":["jtbd","motivation","product","framework"],"skillArea":"productThinking"},
  {"id":"p15","title":"Cross-functional Influence: Design Without Authority","content":"Getting design decisions shipped at MAANG: (1) Build shared context - everyone understands user problem before solutions. (2) Use data as common language. (3) Make cost of NOT doing it clear - technical debt, user churn, support burden. (4) Prototype the decision, not the solution. (5) Find the aligned incentive - connect your proposal to engineering and PM goals. (6) Document decisions in writing. MAANG truth: the best design nobody ships is worse than a mediocre design that does. Influence is a design skill.","source":"MAANG Curated","url":"internal","tags":["influence","cross-functional","leadership","process"],"skillArea":"communication"},
]

FRAMEWORKS = [
  {"id":"f1","title":"Stanford d.school: 5-Stage Design Thinking Process","content":"Full framework: (1) EMPATHIZE: immerse in user world. Methods: interviews, observation, shadowing. Output: empathy map (says, thinks, does, feels). (2) DEFINE: synthesize into POV: [User] needs [need] because [insight]. Test: does your insight surprise you? If not, go deeper. (3) IDEATE: diverge before converging. HMW questions. Crazy 8s (8 sketches in 8 minutes). Volume before quality. (4) PROTOTYPE: build to learn. It should take 1/10th the time of the real thing. (5) TEST: 5 users finds 85% of usability issues. Observe silently. Iterate. MAANG bar: can you justify every design decision with research from stage 1?","source":"Stanford d.school","url":"https://dschool.stanford.edu/resources/design-thinking-bootleg","tags":["design-thinking","process","stanford","framework"],"skillArea":"uxExecution"},
  {"id":"f2","title":"Amazon: Working Backwards from Customer","content":"Amazon product process: write the press release FIRST. PR/FAQ structure: (1) Headline: one sentence, what is this and for whom. (2) Problem paragraph: what is the problem today, be specific. (3) Solution paragraph: how does the product solve it. (4) Customer quote: emotional success story. (5) FAQ: hard questions about feasibility, cost, risk. For designers: this forces clarity before pixels. Reverses design then justify to justify then design. MAANG bar: if you cannot write the press release, you do not understand the problem deeply enough.","source":"Amazon Design / MAANG Curated","url":"internal","tags":["amazon","working-backwards","prfaq","product"],"skillArea":"productThinking"},
  {"id":"f3","title":"Atomic Design: Building Scalable Design Systems","content":"Brad Frost methodology: (1) ATOMS: basic UI elements: button, input, label, color token, type style. (2) MOLECULES: purposeful combinations: search field = input + button + label. (3) ORGANISMS: complex sections: navigation, hero, card grid, data table. (4) TEMPLATES: page-level layouts with placeholder content. (5) PAGES: templates with real content. Component API design: composition over inheritance, controlled vs uncontrolled components, sensible defaults with full override. MAANG bar: a designer who understands token architecture thinks in systems not pixels.","source":"Brad Frost / MAANG Curated","url":"https://atomicdesign.bradfrost.com/","tags":["design-systems","atomic-design","components","scale"],"skillArea":"systemsThinking"},
  {"id":"f4","title":"MIT System Dynamics: Causal Loop Diagrams","content":"CLD in product design: map causal relationships in your product ecosystem. Elements: Variables (things that change: DAU, churn, content quality), Causal links (arrows showing influence: + for same direction, - for opposite), Loops (reinforcing + or balancing -), Delays (time gaps between cause and effect). Exercise: draw the CLD for your top feature. What reinforcing loops does it create? What balancing loops exist? MAANG system design: designers who think in systems spot edge cases before they become incidents.","source":"MIT System Dynamics","url":"https://ocw.mit.edu/courses/res-15-004-principles-of-system-dynamics-spring-2007/","tags":["system-dynamics","causal-loops","mit","systems"],"skillArea":"systemsThinking"},
  {"id":"f5","title":"Google PAIR: Human-AI Interaction Guidelines","content":"Google People + AI Research guidelines: (1) Make AI capabilities and limitations explicit. (2) Design for the feedback loop: how do users teach the AI when it is wrong? Make correction intuitive. (3) Gradual onboarding of AI complexity. (4) Transparency about data use. (5) Maintain human agency: AI should suggest not dictate unless user explicitly delegates. (6) Graceful degradation: design the non-AI fallback first. (7) Explain confidence: show when the AI is uncertain. MAANG bar: what happens when your AI is wrong is always the interview question.","source":"Google PAIR","url":"https://pair.withgoogle.com/guidebook/","tags":["ai","google-pair","human-ai","trust"],"skillArea":"aiUnderstanding"},
  {"id":"f6","title":"Design Tokens: Architecture for Scalable Visual Systems","content":"Token hierarchy: (1) GLOBAL tokens: raw values. color-blue-500 = #3B82F6. Not semantic. (2) ALIAS/SEMANTIC tokens: contextual meaning. color-action-primary references color-blue-500. Expresses intent. (3) COMPONENT tokens: scoped overrides. button-bg-primary references color-action-primary. Naming: category-property-variant-state (color-text-secondary-hover). Benefits: global rebrand changes one token; theming changes semantic layer without touching components. No token governance equals design system entropy.","source":"MAANG Curated / Design Systems","url":"internal","tags":["design-tokens","design-systems","architecture","governance"],"skillArea":"systemsThinking"},
  {"id":"f7","title":"Information Architecture: Card Sorting and Tree Testing","content":"IA validation methods: CARD SORTING: users organize topics into groups. Open sort: users create own categories (use for navigation design). Closed sort: users assign to predefined categories (validate existing IA). Minimum 15-20 participants. Output: similarity matrix, dendrogram. TREE TESTING: users find tasks in text-only navigation. No visual design, pure IA test. Success rate above 80% = valid IA. Findability below 70% = redesign. MAANG bar: never argue about navigation with stakeholders - run a card sort and let users decide with data.","source":"MAANG Curated / NN Group","url":"https://www.nngroup.com/articles/card-sorting-definition/","tags":["ia","card-sorting","tree-testing","navigation"],"skillArea":"uxExecution"},
  {"id":"f8","title":"Heuristic Evaluation: Nielsen 10 Usability Heuristics","content":"Nielsen 10 heuristics: (1) Visibility of system status. (2) Match between system and real world. (3) User control and freedom (undo/redo). (4) Consistency and standards. (5) Error prevention. (6) Recognition over recall. (7) Flexibility and efficiency (shortcuts for experts). (8) Aesthetic and minimalist design. (9) Help users recognize, diagnose, recover from errors. (10) Help and documentation. Severity scale 0-4. MAANG: heuristic evaluation in 2 hours finds 40-60% of usability issues.","source":"Nielsen Norman Group","url":"https://www.nngroup.com/articles/ten-usability-heuristics/","tags":["heuristics","usability","evaluation","nielsen"],"skillArea":"uxExecution"},
  {"id":"f9","title":"Google Ventures: Design Sprint Methodology","content":"5-day Design Sprint: DAY 1 (Map): define challenge, draw product map, choose target. DAY 2 (Sketch): lightning demos, crazy 8s, solution sketches. DAY 3 (Decide): critique, vote, create storyboard. DAY 4 (Prototype): build realistic prototype in Figma or Keynote. DAY 5 (Test): 5 user interviews. Why 5 users: enough to find major problems, not so many it takes weeks. Use sprint when: stakes are high, problem is defined but solution unknown, team alignment needed.","source":"Google Ventures","url":"https://www.gv.com/sprint/","tags":["design-sprint","google","process","rapid-validation"],"skillArea":"productThinking"},
  {"id":"f10","title":"Accessibility: ARIA Patterns and Semantic HTML","content":"W3C ARIA authoring practices: (1) Use semantic HTML first. Native button gets keyboard focus, enter/space activation, screen reader announcements for free. (2) ARIA roles: landmark roles (main, nav, aside, header, footer) help screen reader navigation. (3) ARIA states: aria-expanded, aria-selected, aria-checked for dynamic components. (4) ARIA live regions: aria-live polite for async status updates. (5) Focus management: after modal opens, focus moves to modal; after closing, focus returns to trigger. MAANG bar: build a custom dropdown without ARIA and you will fail a WCAG audit.","source":"W3C ARIA Authoring Practices","url":"https://www.w3.org/WAI/ARIA/apg/","tags":["aria","semantic-html","accessibility","w3c"],"skillArea":"uxExecution"},
  {"id":"f11","title":"UX Writing: Content-First Design","content":"Content-first principles: (1) Write real copy before designing. Lorem ipsum hides layout problems. (2) Labels are UX decisions: Submit vs Save my changes vs Continue communicate different things. (3) Error messages must answer 3 questions: what went wrong, why, how to fix. Never An error occurred. (4) Microcopy creates trust: empty states, loading messages, confirmations are designed not written by engineers. (5) Plain language: grade 8 reading level for consumer products. (6) Internationalization-first: design for longest translated string (German is 30% longer than English).","source":"MAANG Curated","url":"internal","tags":["ux-writing","content","microcopy","language"],"skillArea":"uxExecution"},
  {"id":"f12","title":"Prioritization: RICE Scoring for Design Decisions","content":"RICE scoring (Intercom): Reach times Impact times Confidence divided by Effort. Reach: users affected per time period. Impact: 0.25 minimal to 3 massive. Confidence: percent sure about estimates. Effort: person-months. Higher score = higher priority. ICE scoring (simpler): Impact times Confidence times Ease (1-10 each). How designers use this: to move from I think we should do X to X has 3x the RICE score of Y, here is the data. MAANG bar: designers who prioritize using data are treated as product partners not pixel pushers.","source":"MAANG Curated / Intercom","url":"https://www.intercom.com/blog/rice-simple-prioritization-for-product-managers/","tags":["prioritization","rice","ice","decision-making"],"skillArea":"productThinking"},
  {"id":"f13","title":"Responsive Design: Mobile-First and Fluid Grids","content":"Mobile-first design system: (1) Start with smallest viewport: forces content prioritization. (2) Progressive enhancement: layer complexity for larger screens. (3) Fluid grids: columns as percentages. 4-column mobile, 8-column tablet, 12-column desktop. (4) Breakpoints by content needs: typical 320, 768, 1024, 1440. (5) Touch targets: 44x44px minimum (Apple HIG), 48x48dp (Material Design). (6) Thumb zone: most reachable area is bottom two-thirds of screen. Primary actions go there. MAANG bar: why does your design decision differ between mobile and desktop? Screen size is not a sufficient answer.","source":"MAANG Curated","url":"internal","tags":["responsive","mobile-first","grid","layout"],"skillArea":"uxExecution"},
]

GUIDELINES = [
  {"id":"g1","title":"WCAG 2.1 Level AA Checklist - Critical Requirements","content":"Must-pass WCAG 2.1 AA: TEXT: min 4.5:1 contrast normal, 3:1 large (18pt+). IMAGES: all have alt text, decorative images have empty alt. VIDEO: all prerecorded video has captions. KEYBOARD: all functionality by keyboard, visible focus indicator, no keyboard traps. FORMS: all inputs have labels, errors identified in text, required fields indicated. NAVIGATION: skip link, page title describes content, logical focus order. TIME LIMITS: users can extend or disable session timeouts. FLASHING: nothing flashes more than 3 times per second. LANGUAGE: page language declared in HTML. MAANG: accessibility audits are part of launch criteria at Google, Meta, Amazon.","source":"W3C WCAG 2.1","url":"https://www.w3.org/TR/WCAG21/","tags":["wcag","checklist","accessibility","compliance"],"skillArea":"uxExecution"},
  {"id":"g2","title":"Material Design 3: Google Design System Guidelines","content":"Material Design 3 core: (1) Dynamic color: system generates scheme from wallpaper. Design for the color system. (2) Typography scale: Display 57/45/36, Headline 32/28/24, Title 22/16/14, Body 16/14/12, Label 14/12/11. (3) Elevation: tonal color instead of shadow in dark mode. (4) Shape: small 4dp, medium 12dp, large 16dp. Expressive shape equals brand personality. (5) Adaptive layouts: canonical layouts are list-detail, supporting pane, feed. (6) Motion: emphasized easing for screen transitions, standard for component animations. Material Design is Google externalized internal standards.","source":"Google Material Design 3","url":"https://m3.material.io/","tags":["material-design","google","design-system","guidelines"],"skillArea":"uxExecution"},
  {"id":"g3","title":"Microsoft Inclusive Design: Recognize Exclusion","content":"Microsoft methodology: (1) Recognize exclusion: exclusion is a mismatch between person and environment. Not user problem, design problem. (2) Learn from diversity: people with disabilities are expert problem-solvers. (3) Solve for one, extend to many. Spectrum of ability: permanent arm loss, temporary broken arm, situational new parent holding baby. Same design solution serves all three contexts. MAANG bar: how does your design account for users in suboptimal conditions? What is your 2G, low-battery, one-hand scenario?","source":"Microsoft Inclusive Design","url":"https://inclusive.microsoft.design/","tags":["inclusive","microsoft","exclusion","disability"],"skillArea":"uxExecution"},
  {"id":"g4","title":"Apple Human Interface Guidelines: Core Principles","content":"Apple HIG: (1) Aesthetic integrity: visual appearance matches purpose. (2) Consistency: use system components when possible. Deviations require strong justification. (3) Direct manipulation: prefer direct over menus. (4) Feedback: acknowledge every user action. (5) User control: users make decisions, not the app. iOS: 44x44pt minimum touch targets, safe area insets respected, Dynamic Type support required. MAANG bar: knowing platform guidelines signals that you study how platforms earn user trust.","source":"Apple HIG","url":"https://developer.apple.com/design/human-interface-guidelines/","tags":["apple","hig","ios","guidelines"],"skillArea":"uxExecution"},
]

BOOKS = [
  {"id":"b1","title":"The Design of Everyday Things - Don Norman","content":"Core concepts: affordances (what an object communicates it can do), signifiers (signals communicating affordances), mapping (relationship between controls and effects), feedback (communicating results of actions), conceptual models (user mental model of how system works). Fundamental principle: when users make errors, blame the design not the user. Norman doors fail because design violates mental models. MAANG relevance: every design critique should reference at least one Norman principle.","source":"OpenLibrary","url":"https://openlibrary.org/works/OL24132429W/","tags":["book","affordances","norman","usability"],"skillArea":"uxExecution"},
  {"id":"b2","title":"Thinking Fast and Slow - Daniel Kahneman","content":"System 1 (fast, automatic, emotional, unconscious) vs System 2 (slow, deliberate, logical). Design implications: (1) Cognitive ease: familiar clear content processed by System 1. (2) Anchoring: first number presented biases all subsequent estimates. (3) Loss aversion: losses hurt twice as much as equivalent gains. Frame design as avoiding loss. (4) Peak-end rule: users judge experiences by peak moment and ending, not average. Design the peak and the end deliberately.","source":"OpenLibrary","url":"https://openlibrary.org/works/OL15534867W/","tags":["book","psychology","cognitive-bias","kahneman"],"skillArea":"productThinking"},
  {"id":"b3","title":"Hooked: How to Build Habit-Forming Products - Nir Eyal","content":"Hook Model: (1) TRIGGER: external (notification, email) or internal (boredom, loneliness, FOMO). Internal triggers are stickier. (2) ACTION: simplest behavior in anticipation of reward. Fogg behavior model: B=MAT (Motivation times Ability times Trigger). Reduce friction ruthlessly. (3) VARIABLE REWARD: rewards of tribe (social validation), hunt (information, resources), self (mastery, completion). Variable means unpredictable means more engagement. (4) INVESTMENT: user puts in data, content, followers. MAANG ethical bar: which hooks create genuine value vs exploit vulnerability?","source":"OpenLibrary","url":"https://openlibrary.org/works/OL17819915W/","tags":["book","hooks","behavior","engagement","habits"],"skillArea":"productThinking"},
  {"id":"b4","title":"Don't Make Me Think - Steve Krug","content":"Web usability: (1) Users should never have to think about how to use your site. (2) Users scan, not read. Design for scanning: clear hierarchy, meaningful headings, short paragraphs, lists. (3) Billboard design: navigation must be instantly clear. (4) Omit needless words: half the words can be cut without loss. (5) Happy talk is bad: welcome to our site wastes screen space. (6) Test with 3 users: reveals most critical problems even with tiny samples. Test early and often.","source":"OpenLibrary","url":"https://openlibrary.org/works/OL7629074W/","tags":["book","usability","web","krug","scanning"],"skillArea":"uxExecution"},
  {"id":"b5","title":"Sprint: How to Solve Big Problems - Jake Knapp","content":"Design Sprint 5-day process: Monday map, Tuesday sketch, Wednesday decide, Thursday prototype, Friday test with 5 users. Key insight: compresses months of work into one week by focusing on prototyping and testing rather than building. The prototype appears real but built in one day. Goal: answer one critical strategic question. Why 5 users: enough to find major problems, not so many it takes weeks. Use sprint when stakes are high, problem defined but solution unknown, team alignment needed.","source":"OpenLibrary","url":"https://openlibrary.org/works/OL19681452W/","tags":["book","sprint","google","prototype","process"],"skillArea":"productThinking"},
  {"id":"b6","title":"Lean UX - Jeff Gothelf and Josh Seiden","content":"Lean UX applies lean startup to UX: (1) Assumptions first: articulate what you believe to be true about users, business, design. (2) Hypotheses: We believe [doing X] for [user] will achieve [outcome]. (3) MVP: smallest experiment that tests the hypothesis. (4) Feedback and learning: measure outcomes not outputs. Did behavior change? (5) Continuous improvement: no design phase, design is ongoing. Collaborative design: designer plus PM plus engineer participate together. No more handoff documents. MAANG relevance: Lean UX is the operating model at most MAANG product teams today.","source":"OpenLibrary","url":"https://openlibrary.org/works/OL19649453W/","tags":["book","lean","hypothesis","agile","collaboration"],"skillArea":"productThinking"},
]

ARTICLES = [
  {"id":"a1","title":"Google Design: Designing for the Next Billion Users","content":"Designing for emerging markets: (1) Low-end Android with 512MB RAM: no heavy animations, reduce app size. (2) Intermittent connectivity: offline-first design, graceful degradation. (3) Shared devices: no persistent login assumptions, privacy by default. (4) Expensive data: reduce consumption, compress images. (5) Low literacy: icon-forward UI, visual instructions over text. MAANG bar: can your product work on a 50 dollar Android with 2G connectivity? If not, you are excluding 2 billion potential users.","source":"Google Design","url":"https://design.google/library/","tags":["google","global","emerging-markets","inclusion"],"skillArea":"productThinking"},
  {"id":"a2","title":"Microsoft: Designing Accessible AI","content":"Microsoft Accessibility plus AI: (1) AI must never create new accessibility barriers. If AI generates content, alt text must also be generated. (2) Train on diverse data: AI trained on homogeneous data fails for diverse users. (3) Human override always available. (4) Transparent AI behavior: screen readers must convey AI-generated content and uncertainty. (5) Test with disabled users: automated testing catches only 30 percent of issues. MAANG bar: disability community members on your research panel is a requirement, not optional.","source":"Microsoft Design","url":"https://www.microsoft.com/en-us/ai/responsible-ai","tags":["microsoft","ai","accessibility","responsible-ai"],"skillArea":"aiUnderstanding"},
  {"id":"a3","title":"NN Group: The Paradox of the Active User","content":"John Carroll paradox: users begin using software immediately without reading documentation and continue using only the small subset of features they discovered first. Implications: (1) Onboarding must teach by doing not explaining. (2) Features buried in menus are features that do not exist. (3) Progressive disclosure: show only what is needed now. (4) Contextual help beats documentation. (5) Empty states are teaching moments. MAANG bar: your onboarding flow is the most high-stakes UX you will design. Most users churn within the first session.","source":"Nielsen Norman Group","url":"https://www.nngroup.com/articles/paradox-of-the-active-user/","tags":["onboarding","progressive-disclosure","nngroup","learning"],"skillArea":"uxExecution"},
  {"id":"a4","title":"Adobe: The Role of Motion in UX","content":"Motion design principles: (1) Motion communicates state: what changed, where it came from, where it went. (2) Duration: 200-500ms for most transitions. Under 100ms imperceptible. Over 500ms slow and frustrating. (3) Easing: ease-out for elements entering screen, ease-in for leaving, ease-in-out for looping. (4) Natural motion: objects obey physics, weight, momentum, bounce. (5) Purposeful motion: every animation must serve a communicative purpose. Decorative animation wastes cognitive resources.","source":"Adobe Design","url":"https://blog.adobe.com/en/topics/design","tags":["motion","animation","adobe","microinteractions"],"skillArea":"uxExecution"},
]

all_items = PRINCIPLES + FRAMEWORKS + GUIDELINES + BOOKS + ARTICLES

db = {
  "lastUpdated": datetime.now(timezone.utc).isoformat(),
  "sources": [
    {"name": "MIT OpenCourseWare", "url": "https://ocw.mit.edu"},
    {"name": "Stanford d.school", "url": "https://dschool.stanford.edu"},
    {"name": "W3C WAI/WCAG", "url": "https://www.w3.org/WAI/"},
    {"name": "OpenLibrary", "url": "https://openlibrary.org"},
    {"name": "Google Design", "url": "https://design.google"},
    {"name": "Microsoft Inclusive Design", "url": "https://inclusive.microsoft.design"},
    {"name": "Nielsen Norman Group", "url": "https://www.nngroup.com"},
    {"name": "MAANG Curated Knowledge", "url": "internal"},
  ],
  "principles": PRINCIPLES,
  "frameworks": FRAMEWORKS,
  "guidelines": GUIDELINES,
  "courses": [],
  "books": BOOKS,
  "articles": ARTICLES,
  "bySkill": {
    "productThinking": ["p2","p3","p8","p9","p14","f2","f9","f12","b2","b3","b5","b6","a1"],
    "uxExecution": ["p4","p5","p6","p7","f1","f7","f8","f10","f11","f13","g1","g2","g3","g4","b1","b4","a3","a4"],
    "systemsThinking": ["p1","p10","f3","f4","f6"],
    "aiUnderstanding": ["p11","p13","f5","a2"],
    "communication": ["p12","p15","p5"],
  },
  "stats": {
    "total": len(all_items),
    "principles": len(PRINCIPLES),
    "frameworks": len(FRAMEWORKS),
    "guidelines": len(GUIDELINES),
    "courses": 0,
    "books": len(BOOKS),
    "articles": len(ARTICLES),
  }
}

os.makedirs(os.path.join(ROOT, 'public'), exist_ok=True)
with open(OUT, 'w', encoding='utf-8') as f:
    json.dump(db, f, indent=2, ensure_ascii=False)

print(f"Knowledge base built: {len(all_items)} items -> public/knowledge.json")
print(f"  Principles:{len(PRINCIPLES)}  Frameworks:{len(FRAMEWORKS)}  Guidelines:{len(GUIDELINES)}  Books:{len(BOOKS)}  Articles:{len(ARTICLES)}")
